# Generated by Django 4.2.7 on 2025-05-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_client_owner_mailing_is_activated_mailing_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [("set_is_activated", "Может отключать рассылку")],
                "verbose_name": "Расссылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
